### PR TITLE
Search, content creation, ancestor child relationships, etc.

### PR DESCRIPTION
**Pull request by jesselang**
First off, thanks for starting this library. I need to create content, so I looked through the forks, and here was a fork with the functionality I'd like to use. I figured I'd bring it to your attention by way of a pull request in case you find it worth merging in. Thanks!

### CODE REVIEW

**Comment by seppestas** [comment]
Thanks, looks interesting 👍

To be honest I don't actively use this library anymore myself (though I still use Confluence, so maybe I'll find an new use-case for it one day 😀).

I'll take a look at these new features and merge them when I find some time this week.

**Comment by jesselang** [comment]
Thanks for the quick response. I'm primarily using the content creation and ancestry stuff right now. There's a few rough edges in the code, to be sure, but I have a future use case for the search too. If you look it over but decide you don't want to merge it wholesale, I might be able to part it out and clean it up a bit. Thanks!

**Comment by zonorti** [comment]
Any plans to get it merged? 
I would also like to have content creation functionality.

**Comment by seppestas** [comment]
I didn't find the time yet to properly review and test this, I'm currently a bit busy with some other projects. As stated before, I don't maintain the project this library was made for anymore.

From first glance I already spotted some issues with this PR, meaning I won't merge it as-is:
- I don't really like the prints to stdout (I understand it's useful while debugging, but I think it should be removed or wrapped in a logging library to prevent confusion when it is used in production).
- I don't think returning a non-`nill` response when an error occurred is a good idea.

**Comment by jesselang** [comment]
I'm planning to use this functionality for an app I'm working on, so I have an interest in getting this functionality in either here, or in my fork. I'll comment here when I have that done. It's a free-time project, so no timelines here. Thanks all!

**Pull request closed without merging**
